### PR TITLE
Added code duh

### PR DESCRIPTION
**Pull request by kttykat**
Added reaction role system similar to discord.gg/photography requested by ari ( https://canary.discord.com/channels/913668807015407646/913668807015407649/1036094220047491152 ) ( keep your $5 ari )

### CODE REVIEW

**Review by Neesh774 — CHANGES_REQUESTED** [review]
Can you uncomment the line you commented in CommandHandler? You broke every command lmao

**Comment by kttykat** [comment]
yeah i can give me a second

**Review by Neesh774 — CHANGES_REQUESTED** [review]
Pls test your code before you make a pr, /roles command doesn't work

**Review by Neesh774 — CHANGES_REQUESTED** [review]
image
There are still a few issues with your JSON. Also, the experience level and country should only let users select a single role.

**Comment by Neesh774** [comment]
There's another particularly large issue with your code as well. Because you're handling all select menu interactions in your RoleHandler, you've broken every other select menu interaction. You need to use our custom Embeds feature in the same way I was using them previously, because the files in the /embeds folder let you react to certain interactions based on customId without taking control of all interactions of a certain type. Please look through the old reactionRoles.ts file in there to get an idea for how they work.

**Comment by kttykat** [comment]
alright, ill look through it when i have some free time

**Pull request closed without merging**
