### PR TITLE
Reaction role

### LINKED ISSUE #6: Change reactionRoles Embed
image
Create an interaction like this in the /reactionRoles.ts embed file. Note that it isn't ephemeral either, so it has to persist for each user independently.

### PR DESCRIPTION
**Pull request by GamerCreator1**
Closes #6

### CODE REVIEW

**Review by Neesh774 — CHANGES_REQUESTED** [review]
Can you add an ephemeral reply to the /roles command, something like "Messages sent!"?

Also, can you add some error catching so the bot doesn't crash if it can't give a role, or something like that?

**Comment by Neesh774** [comment]
Could you add some sort of emojis/formatting to make the messages pop out more? Also, there's no need to add the "(Skip if you'd rather not disclose)" in pronouns since they're all optional anyways

**Review by Neesh774 — CHANGES_REQUESTED** [review]
Could you add a reply to the initial command in the /roles command?

**Comment by GamerCreator1** [comment]
> Could you add a reply to the initial command in the /roles command?

sure

**Review by Neesh774 — APPROVED** [review]

**Pull request merged**
